import type { NewExercicio } from '../schema/index.js';

export const exerciciosSeed: NewExercicio[] = [
  // ============ PEITO (6) ============
  {
    nome: 'Supino reto com barra',
    slug: 'supino-reto-barra',
    grupoMuscularPrimario: 'peito',
    gruposSecundarios: ['triceps', 'ombro'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'empurrar_horizontal',
    instrucoes:
      'Deitado no banco, mantenha os pés apoiados no chão. Desça a barra controladamente até o peito. Empurre de volta sem travar os cotovelos.',
    escopo: 'publico',
  },
  {
    nome: 'Supino reto com halteres',
    slug: 'supino-reto-halteres',
    grupoMuscularPrimario: 'peito',
    gruposSecundarios: ['triceps', 'ombro'],
    equipamento: 'halter',
    categoria: 'composto',
    padraoMovimento: 'empurrar_horizontal',
    instrucoes:
      'Mantenha os punhos alinhados com os antebraços. Desça até a altura do peito sem perder a tensão.',
    escopo: 'publico',
  },
  {
    nome: 'Supino inclinado com halteres',
    slug: 'supino-inclinado-halteres',
    grupoMuscularPrimario: 'peito',
    gruposSecundarios: ['ombro', 'triceps'],
    equipamento: 'halter',
    categoria: 'composto',
    padraoMovimento: 'empurrar_horizontal',
    instrucoes: 'Banco a 30-45°. Foco no peitoral superior.',
    escopo: 'publico',
  },
  {
    nome: 'Crucifixo na máquina (peck deck)',
    slug: 'crucifixo-maquina',
    grupoMuscularPrimario: 'peito',
    gruposSecundarios: [],
    equipamento: 'maquina',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Movimento de adução. Mantenha cotovelos levemente flexionados.',
    escopo: 'publico',
  },
  {
    nome: 'Crossover no cabo',
    slug: 'crossover-cabo',
    grupoMuscularPrimario: 'peito',
    gruposSecundarios: [],
    equipamento: 'cabo',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Inclinação leve do tronco. Junte as mãos na frente do quadril.',
    escopo: 'publico',
  },
  {
    nome: 'Flexão de braço',
    slug: 'flexao-braco',
    grupoMuscularPrimario: 'peito',
    gruposSecundarios: ['triceps', 'ombro', 'core'],
    equipamento: 'peso_corporal',
    categoria: 'composto',
    padraoMovimento: 'empurrar_horizontal',
    instrucoes: 'Corpo alinhado, abdômen contraído. Cotovelos a ~45° do tronco.',
    escopo: 'publico',
  },

  // ============ COSTAS (9) ============
  {
    nome: 'Puxada na barra fixa',
    slug: 'barra-fixa',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['biceps'],
    equipamento: 'peso_corporal',
    categoria: 'composto',
    padraoMovimento: 'puxar_vertical',
    instrucoes: 'Pegada pronada na largura dos ombros. Eleve o queixo até a altura da barra.',
    escopo: 'publico',
  },
  {
    nome: 'Puxada na polia alta',
    slug: 'puxada-polia-alta',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['biceps'],
    equipamento: 'cabo',
    categoria: 'composto',
    padraoMovimento: 'puxar_vertical',
    instrucoes: 'Puxe a barra até a altura do peito. Foque em puxar com os cotovelos.',
    escopo: 'publico',
  },
  {
    nome: 'Remada curvada com barra',
    slug: 'remada-curvada-barra',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['biceps', 'trapezio'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'puxar_horizontal',
    instrucoes: 'Tronco inclinado ~45°. Puxe a barra até o abdômen.',
    escopo: 'publico',
  },
  {
    nome: 'Remada baixa no cabo',
    slug: 'remada-baixa-cabo',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['biceps'],
    equipamento: 'cabo',
    categoria: 'composto',
    padraoMovimento: 'puxar_horizontal',
    instrucoes: 'Costas eretas, ombros para trás na puxada. Aproxime as escápulas.',
    escopo: 'publico',
  },
  {
    nome: 'Remada unilateral com halter',
    slug: 'remada-unilateral-halter',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['biceps'],
    equipamento: 'halter',
    categoria: 'composto',
    padraoMovimento: 'puxar_horizontal',
    instrucoes: 'Apoie joelho e mão no banco. Puxe o halter até o quadril.',
    escopo: 'publico',
  },
  {
    nome: 'Remada cavalinho (T-bar)',
    slug: 'remada-cavalinho',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['biceps', 'trapezio'],
    equipamento: 'maquina',
    categoria: 'composto',
    padraoMovimento: 'puxar_horizontal',
    instrucoes: 'Tronco inclinado. Puxe o peso até a altura do umbigo.',
    escopo: 'publico',
  },
  {
    nome: 'Pullover com halter',
    slug: 'pullover-halter',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['peito'],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Deitado no banco. Desça o halter atrás da cabeça com cotovelos levemente flexionados.',
    escopo: 'publico',
  },
  {
    nome: 'Levantamento terra',
    slug: 'levantamento-terra',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['pernas_posterior', 'pernas_gluteo', 'trapezio'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'flexao_quadril',
    instrucoes: 'Costas neutras. Empurre o chão com os pés. Quadril e ombros sobem juntos.',
    escopo: 'publico',
  },
  {
    nome: 'Hiperextensão lombar',
    slug: 'hiperextensao-lombar',
    grupoMuscularPrimario: 'costas',
    gruposSecundarios: ['pernas_gluteo', 'pernas_posterior'],
    equipamento: 'maquina',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Não force a hiperextensão. Pare em linha com o tronco.',
    escopo: 'publico',
  },

  // ============ PERNAS QUADRÍCEPS (5) ============
  {
    nome: 'Agachamento livre',
    slug: 'agachamento-livre',
    grupoMuscularPrimario: 'pernas_quadriceps',
    gruposSecundarios: ['pernas_gluteo', 'core'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'agachar',
    instrucoes: 'Pés na largura dos ombros. Desça até coxa paralela ou abaixo, mantendo o tronco firme.',
    escopo: 'publico',
  },
  {
    nome: 'Leg press 45°',
    slug: 'leg-press-45',
    grupoMuscularPrimario: 'pernas_quadriceps',
    gruposSecundarios: ['pernas_gluteo'],
    equipamento: 'maquina',
    categoria: 'composto',
    padraoMovimento: 'agachar',
    instrucoes: 'Pés posicionados centralmente na plataforma. Não trave os joelhos no topo.',
    escopo: 'publico',
  },
  {
    nome: 'Cadeira extensora',
    slug: 'cadeira-extensora',
    grupoMuscularPrimario: 'pernas_quadriceps',
    gruposSecundarios: [],
    equipamento: 'maquina',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Pause 1s no topo. Desça controlando.',
    escopo: 'publico',
  },
  {
    nome: 'Avanço com halteres (passada)',
    slug: 'avanco-halteres',
    grupoMuscularPrimario: 'pernas_quadriceps',
    gruposSecundarios: ['pernas_gluteo'],
    equipamento: 'halter',
    categoria: 'composto',
    padraoMovimento: 'agachar',
    instrucoes: 'Passo à frente, joelho da perna de trás próximo ao chão. Volte empurrando o calcanhar.',
    escopo: 'publico',
  },
  {
    nome: 'Hack squat',
    slug: 'hack-squat',
    grupoMuscularPrimario: 'pernas_quadriceps',
    gruposSecundarios: ['pernas_gluteo'],
    equipamento: 'maquina',
    categoria: 'composto',
    padraoMovimento: 'agachar',
    instrucoes: 'Pés à frente da plataforma. Desça até 90° sem perder o contato lombar.',
    escopo: 'publico',
  },

  // ============ PERNAS POSTERIOR (3) ============
  {
    nome: 'Stiff com barra',
    slug: 'stiff-barra',
    grupoMuscularPrimario: 'pernas_posterior',
    gruposSecundarios: ['pernas_gluteo', 'costas'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'flexao_quadril',
    instrucoes: 'Joelhos levemente flexionados. Empurre o quadril para trás. Costas neutras.',
    escopo: 'publico',
  },
  {
    nome: 'Mesa flexora',
    slug: 'mesa-flexora',
    grupoMuscularPrimario: 'pernas_posterior',
    gruposSecundarios: [],
    equipamento: 'maquina',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Quadril fixo na mesa. Flexione o joelho até quase tocar o glúteo.',
    escopo: 'publico',
  },
  {
    nome: 'Cadeira flexora',
    slug: 'cadeira-flexora',
    grupoMuscularPrimario: 'pernas_posterior',
    gruposSecundarios: [],
    equipamento: 'maquina',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Sentado. Flexione o joelho controlando a fase excêntrica.',
    escopo: 'publico',
  },

  // ============ PERNAS GLÚTEO (3) ============
  {
    nome: 'Hip thrust com barra',
    slug: 'hip-thrust-barra',
    grupoMuscularPrimario: 'pernas_gluteo',
    gruposSecundarios: ['pernas_posterior'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'flexao_quadril',
    instrucoes: 'Costa apoiada no banco. Empurre o quadril para cima até linha reta.',
    escopo: 'publico',
  },
  {
    nome: 'Elevação pélvica (glute bridge)',
    slug: 'elevacao-pelvica',
    grupoMuscularPrimario: 'pernas_gluteo',
    gruposSecundarios: ['pernas_posterior'],
    equipamento: 'peso_corporal',
    categoria: 'isolado',
    padraoMovimento: 'flexao_quadril',
    instrucoes: 'Deitado de costas. Eleve o quadril contraindo glúteos no topo.',
    escopo: 'publico',
  },
  {
    nome: 'Coice na polia',
    slug: 'coice-polia',
    grupoMuscularPrimario: 'pernas_gluteo',
    gruposSecundarios: ['pernas_posterior'],
    equipamento: 'cabo',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Tornozelo na caneleira. Estenda o quadril mantendo joelho estável.',
    escopo: 'publico',
  },

  // ============ PERNAS PANTURRILHA (2) ============
  {
    nome: 'Panturrilha em pé na máquina',
    slug: 'panturrilha-em-pe',
    grupoMuscularPrimario: 'pernas_panturrilha',
    gruposSecundarios: [],
    equipamento: 'maquina',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Amplitude máxima. Pause 1s no topo.',
    escopo: 'publico',
  },
  {
    nome: 'Panturrilha sentado',
    slug: 'panturrilha-sentado',
    grupoMuscularPrimario: 'pernas_panturrilha',
    gruposSecundarios: [],
    equipamento: 'maquina',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Foco no sóleo. Movimento lento e controlado.',
    escopo: 'publico',
  },

  // ============ OMBRO (6) ============
  {
    nome: 'Desenvolvimento com halteres',
    slug: 'desenvolvimento-halteres',
    grupoMuscularPrimario: 'ombro',
    gruposSecundarios: ['triceps'],
    equipamento: 'halter',
    categoria: 'composto',
    padraoMovimento: 'empurrar_vertical',
    instrucoes: 'Sentado ou em pé. Empurre os halteres acima da cabeça sem trancar cotovelos.',
    escopo: 'publico',
  },
  {
    nome: 'Desenvolvimento militar com barra',
    slug: 'desenvolvimento-militar',
    grupoMuscularPrimario: 'ombro',
    gruposSecundarios: ['triceps', 'core'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'empurrar_vertical',
    instrucoes: 'Em pé. Empurre a barra acima da cabeça. Glúteos contraídos para proteger a lombar.',
    escopo: 'publico',
  },
  {
    nome: 'Elevação lateral com halteres',
    slug: 'elevacao-lateral',
    grupoMuscularPrimario: 'ombro',
    gruposSecundarios: [],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Cotovelos levemente flexionados. Suba até a altura dos ombros.',
    escopo: 'publico',
  },
  {
    nome: 'Elevação frontal com halter',
    slug: 'elevacao-frontal',
    grupoMuscularPrimario: 'ombro',
    gruposSecundarios: [],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Suba o halter à frente até a altura do ombro. Sem balanço.',
    escopo: 'publico',
  },
  {
    nome: 'Crucifixo invertido (deltóide posterior)',
    slug: 'crucifixo-invertido',
    grupoMuscularPrimario: 'ombro',
    gruposSecundarios: ['costas'],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Tronco inclinado. Abra os braços puxando com escápulas.',
    escopo: 'publico',
  },
  {
    nome: 'Remada alta',
    slug: 'remada-alta',
    grupoMuscularPrimario: 'ombro',
    gruposSecundarios: ['trapezio', 'biceps'],
    equipamento: 'barra',
    categoria: 'composto',
    padraoMovimento: 'puxar_vertical',
    instrucoes: 'Pegada um pouco menor que a largura dos ombros. Cotovelos sobem primeiro.',
    escopo: 'publico',
  },

  // ============ BÍCEPS (4) ============
  {
    nome: 'Rosca direta com barra',
    slug: 'rosca-direta-barra',
    grupoMuscularPrimario: 'biceps',
    gruposSecundarios: ['antebraco'],
    equipamento: 'barra',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Cotovelos colados ao tronco. Sem balanço.',
    escopo: 'publico',
  },
  {
    nome: 'Rosca alternada com halteres',
    slug: 'rosca-alternada',
    grupoMuscularPrimario: 'biceps',
    gruposSecundarios: ['antebraco'],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Supine o punho ao subir. Movimento controlado.',
    escopo: 'publico',
  },
  {
    nome: 'Rosca martelo',
    slug: 'rosca-martelo',
    grupoMuscularPrimario: 'biceps',
    gruposSecundarios: ['antebraco'],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Pegada neutra. Trabalha braquial e braquiorradial.',
    escopo: 'publico',
  },
  {
    nome: 'Rosca scott',
    slug: 'rosca-scott',
    grupoMuscularPrimario: 'biceps',
    gruposSecundarios: [],
    equipamento: 'barra',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Cotovelos apoiados no banco. Foco na fase excêntrica.',
    escopo: 'publico',
  },

  // ============ TRÍCEPS (5) ============
  {
    nome: 'Tríceps na polia (corda)',
    slug: 'triceps-corda',
    grupoMuscularPrimario: 'triceps',
    gruposSecundarios: [],
    equipamento: 'cabo',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Cotovelos fixos. Estenda os braços abrindo a corda no fim.',
    escopo: 'publico',
  },
  {
    nome: 'Tríceps na polia (barra)',
    slug: 'triceps-polia-barra',
    grupoMuscularPrimario: 'triceps',
    gruposSecundarios: [],
    equipamento: 'cabo',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Cotovelos colados ao tronco. Estensão completa.',
    escopo: 'publico',
  },
  {
    nome: 'Tríceps testa',
    slug: 'triceps-testa',
    grupoMuscularPrimario: 'triceps',
    gruposSecundarios: [],
    equipamento: 'barra',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Cotovelos apontados ao teto. Desça a barra próxima à testa.',
    escopo: 'publico',
  },
  {
    nome: 'Tríceps francês com halter',
    slug: 'triceps-frances',
    grupoMuscularPrimario: 'triceps',
    gruposSecundarios: [],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Halter por trás da cabeça. Estenda o braço sem mover o cotovelo.',
    escopo: 'publico',
  },
  {
    nome: 'Mergulho no banco',
    slug: 'mergulho-banco',
    grupoMuscularPrimario: 'triceps',
    gruposSecundarios: ['peito', 'ombro'],
    equipamento: 'peso_corporal',
    categoria: 'composto',
    padraoMovimento: 'empurrar_vertical',
    instrucoes: 'Mãos no banco. Desça até cotovelo a ~90°.',
    escopo: 'publico',
  },

  // ============ ANTEBRAÇO (2) ============
  {
    nome: 'Rosca de punho',
    slug: 'rosca-punho',
    grupoMuscularPrimario: 'antebraco',
    gruposSecundarios: [],
    equipamento: 'barra',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Antebraços apoiados. Movimento curto e controlado.',
    escopo: 'publico',
  },
  {
    nome: 'Rosca inversa',
    slug: 'rosca-inversa',
    grupoMuscularPrimario: 'antebraco',
    gruposSecundarios: ['biceps'],
    equipamento: 'barra',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Pegada pronada. Trabalha braquiorradial e extensores.',
    escopo: 'publico',
  },

  // ============ TRAPÉZIO (2) ============
  {
    nome: 'Encolhimento com halteres',
    slug: 'encolhimento-halteres',
    grupoMuscularPrimario: 'trapezio',
    gruposSecundarios: [],
    equipamento: 'halter',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Eleve os ombros em direção às orelhas. Sem rolar os ombros.',
    escopo: 'publico',
  },
  {
    nome: 'Encolhimento com barra',
    slug: 'encolhimento-barra',
    grupoMuscularPrimario: 'trapezio',
    gruposSecundarios: [],
    equipamento: 'barra',
    categoria: 'isolado',
    padraoMovimento: 'isolado',
    instrucoes: 'Postura ereta. Subida vertical dos ombros.',
    escopo: 'publico',
  },

  // ============ CORE (5) ============
  {
    nome: 'Prancha',
    slug: 'prancha',
    grupoMuscularPrimario: 'core',
    gruposSecundarios: [],
    equipamento: 'peso_corporal',
    categoria: 'isolado',
    padraoMovimento: 'core',
    instrucoes: 'Corpo alinhado. Glúteos contraídos. Respire normalmente.',
    escopo: 'publico',
  },
  {
    nome: 'Abdominal supra',
    slug: 'abdominal-supra',
    grupoMuscularPrimario: 'core',
    gruposSecundarios: [],
    equipamento: 'peso_corporal',
    categoria: 'isolado',
    padraoMovimento: 'core',
    instrucoes: 'Lombar no chão. Suba apenas a parte superior do tronco.',
    escopo: 'publico',
  },
  {
    nome: 'Elevação de pernas',
    slug: 'elevacao-pernas',
    grupoMuscularPrimario: 'core',
    gruposSecundarios: [],
    equipamento: 'peso_corporal',
    categoria: 'isolado',
    padraoMovimento: 'core',
    instrucoes: 'Deitado. Pernas estendidas. Desça sem encostar no chão.',
    escopo: 'publico',
  },
  {
    nome: 'Russian twist',
    slug: 'russian-twist',
    grupoMuscularPrimario: 'core',
    gruposSecundarios: [],
    equipamento: 'peso_corporal',
    categoria: 'isolado',
    padraoMovimento: 'core',
    instrucoes: 'Sentado, tronco inclinado. Gire o tronco lado a lado.',
    escopo: 'publico',
  },
  {
    nome: 'Abdominal na polia (puxada de joelhos)',
    slug: 'abdominal-polia',
    grupoMuscularPrimario: 'core',
    gruposSecundarios: [],
    equipamento: 'cabo',
    categoria: 'isolado',
    padraoMovimento: 'core',
    instrucoes: 'Ajoelhado. Encurte o abdômen levando cotovelos ao chão.',
    escopo: 'publico',
  },
];
